/**
 * Bake 5-mile trade-area demographics for every reference (competitor) facility
 * into lib/facility-demographics.ts, so the map can show them instantly with no
 * runtime Census calls — mirroring how the facilities' coordinates are baked in.
 *
 * Re-run whenever lib/reference-facilities.ts changes:
 *   npx tsx scripts/gen-facility-demographics.ts
 *
 * Requires CENSUS_API_KEY (read from .env.local below).
 */
import { readFileSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, resolve } from 'node:path'
import { REFERENCE_FACILITIES } from '../lib/reference-facilities'
import { fetchDemographics } from '../lib/census-core'
import type { Demographics } from '../types/demographics'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')

// tsx doesn't auto-load .env — pull the Census key out of .env.local ourselves.
function loadEnv(name: string): void {
  if (process.env[name]) return
  try {
    const text = readFileSync(resolve(root, '.env.local'), 'utf8')
    for (const line of text.split('\n')) {
      const m = line.match(/^([A-Z0-9_]+)=(.*)$/)
      if (m && m[1] === name) process.env[name] = m[2].trim().replace(/^["']|["']$/g, '')
    }
  } catch {
    /* no .env.local — rely on the ambient environment */
  }
}

async function main() {
  loadEnv('CENSUS_API_KEY')
  loadEnv('MAPBOX_TOKEN') // optional — drive-time isochrones; falls back to radius if absent
  if (!process.env.CENSUS_API_KEY) {
    console.error('CENSUS_API_KEY not set (checked .env.local). Aborting.')
    process.exit(1)
  }
  console.log(
    process.env.MAPBOX_TOKEN
      ? 'Using drive-time isochrones (MAPBOX_TOKEN set).'
      : 'No MAPBOX_TOKEN — baking 5-mile radius demographics.',
  )

  const out: Record<string, Demographics> = {}
  let ok = 0
  for (const f of REFERENCE_FACILITIES) {
    process.stdout.write(`• ${f.name} … `)
    const demo = await fetchDemographics(f.lat, f.lng)
    if (demo) {
      out[f.name] = demo
      ok++
      console.log(`${demo.totalPopulation.toLocaleString()} people · B${demo.badmintonFit.score}/P${demo.pickleballFit.score}`)
    } else {
      console.log('no data')
    }
  }

  const body =
    `// AUTO-GENERATED by scripts/gen-facility-demographics.ts — do not edit by hand.\n` +
    `// 5-mile trade-area demographics (US Census ACS) per reference facility,\n` +
    `// keyed by facility name. Re-run the script after editing reference-facilities.ts.\n` +
    `import type { Demographics } from '@/types/demographics'\n\n` +
    `export const FACILITY_DEMOGRAPHICS: Record<string, Demographics> = ${JSON.stringify(out, null, 2)}\n`

  const dest = resolve(root, 'lib/facility-demographics.ts')
  writeFileSync(dest, body)
  console.log(`\nWrote ${ok}/${REFERENCE_FACILITIES.length} facilities → lib/facility-demographics.ts`)
}

main()
